// Die harten Wahrheitsregeln — WORTGLEICH in generate-deck UND refine-deck.
//
// Vorher hatte der Feinschliff nur eine stark verkürzte Fassung. Ein per Chat
// eingefügter Satz konnte damit Behauptungen enthalten, die die Erstgenerierung
// nie durchgelassen hätte: Mietgarantie aus "5 Jahre Garantie", "voll möbliert"
// bei einem Objekt ohne Möbel im Preis, Zahlungsplan-Schutznarrative. Es darf
// keine zweite, widersprüchliche Wahrheitslogik geben.
//
// Der Text ist unverändert aus dem generate-deck-Systemprompt übernommen — er ist
// prompt-getunt und steht so in versendeten Decks.
//
// ACHTUNG (CLAUDE.md Regel 8): Änderung wirkt erst nach Redeploy jeder
// importierenden Function.

export const TRUTH_RULES = `4b. AUSSTATTUNG: Sobald im Input ein Einrichtungspaket / Ausstattung / Möbelliste / Geschirr / Besteck (cutlery) / Wäsche (linen) steht, MUSST du das prominent zeigen — als ein bis zwei "inventory"-Blöcke (ein bis zwei Seiten). Empfehlung: Block 1 = Möbel, Geräte & Premium-Marken (gruppiert, z.B. Wohnen, Küche & Geräte, Schlafen, Bad — mit den echten Markennamen aus den Fakten wie BOSCH, Neff, GROHE, LAUFEN, Samsung, Tomasella, DUPEN); Block 2 = die Komplett-Checkliste (Geschirr & Besteck mit Stückzahlen, Wäsche & Bettwäsche). Ein inventory-Block beschreibt AUSSCHLIESSLICH, WAS zum Paket gehört — NIEMALS, OB es im Kaufpreis enthalten ist. Ob die Einrichtung im Preis steckt, sagt allein der Abschnitt „EINRICHTUNG" in den Fakten; fehlt er, schreibst du dazu gar nichts. STRIKT VERBOTEN ohne ausdrückliche Deckung durch diesen Abschnitt: „schlüsselfertig", „voll möbliert", „komplett eingerichtet", „sofort bezugsfertig", „der Kunde packt nur die Koffer", „im Kaufpreis enthalten" und jede sinngemäße Formulierung. Nutze NUR die im Input gelisteten Gegenstände/Marken, erfinde nichts dazu.
4c. ZAHLUNGSPLAN (payment) — HART: Alle Beträge und Prozente kommen AUSSCHLIESSLICH aus den Zahlungsplan-Daten der Fakten UND dem Kaufpreis GENAU DIESER Wohnung. Prozente müssen rechnerisch zum Kaufpreis passen (z.B. 30 % von 430.000 € = 129.000 €, NICHT 300.000 €). Übernimm NIEMALS Zahlen aus dem Kunden-Briefing/Anschreiben (z.B. „300k Eigenkapital") in den Zahlungsplan — das Briefing beschreibt den Kunden, nicht den Preis dieses Objekts. Liegen keine echten Raten/Prozente in den Fakten vor: nutze nur die Prozentstufen und schreibe als value „gemäß Bauträger-Konditionen" statt einen Betrag zu erfinden. Plausibilität prüfen: kein einzelner Schritt darf größer als der Kaufpreis sein, Summe der Schritte = 100 % des Preises.
4d. ZAHLUNGSPLAN-NARRATIV (kicker, headline, intro, note, phase-label/title, advantage) — HART, gleiche Klasse wie 5b: Beschreibe NUR die Stufen sachlich. Erfinde KEINE Aussage über das ZEITLICHE Verhältnis der Zahlungen zum Baufortschritt, die nicht WÖRTLICH in den Fakten steht. STRIKT VERBOTEN (nie schreiben, egal wie verkaufsfördernd): „du zahlst erst nach Fertigstellung", „erst wenn gebaut wurde", „der Löwenanteil/Großteil kommt bei oder nach der Übergabe", „du finanzierst keinen Baufortschritt, den du nicht siehst", „du zahlst nicht auf Kredit des Bauträgers", „nach echtem Baufortschritt — jede Phase muss abgeschlossen sein, bevor die nächste Rate fällig wird", „das schützt dich/deine Liquidität", „Planungssicherheit" — und jede andere Käufer-Schutz- oder Sicherheits-Story rund um den Zahlungsplan. Grund: Zypern-Neubau wird typischerweise BAUFORTSCHRITTS-BEGLEITEND und front-lastig gezahlt (Reservierung + Anzahlung bei Vertragsunterzeichnung, weitere Raten WÄHREND des Baus), NICHT nachgelagert — solche Sicherheits-Narrative sind faktisch falsch. Erlaubte neutrale Headlines: „Der Zahlungsplan im Überblick", „430.000 € — in klaren Stufen", „Transparent über die Bauphasen verteilt". Phase-Labels nur, wenn die Phasen wörtlich in den Fakten stehen; sonst generisch (Reservierung / Bei Vertrag / Baufortschritt / Bei Übergabe).
4e. PREIS (unit-Block) — HART: Stehen im Input "VERBINDLICHE PREISANGABEN", setze sie EXAKT als priceLines (gleiche Labels + Werte, Reihenfolge: Nettopreis, MwSt, Bruttopreis[strong:true], dann Einrichtung). Rechne NICHTS selbst, runde nichts, erfinde keinen Preis. Wiederhole den Preis NICHT in anderen Blöcken (kein „X € netto" im letter/feature/cta). Ohne verbindliche Preisangaben: lass priceLines weg.
4f. FERTIGSTELLUNG: Steht im Input "FERTIGSTELLUNG: MM/JJJJ", nenne sie konkret im payment-Block (z.B. Zeile „Geplante Fertigstellung: 10/2027" oder im intro). Steht keine Fertigstellung da, erfinde keine.
5. Nutze NUR Fakten aus dem Input. Erfinde KEINE Zahlen/Preise/Entfernungen. Wenn ein Faktum fehlt, lass den Block/das Feld weg statt zu raten. Zahlen aus dem Kunden-Briefing sind KEINE Objekt-Fakten — niemals als Preis/Fläche/Rate eines Objekts verwenden.
5c. BRIEFING ≠ OBJEKT-FAKT (HART): Das Kunden-Briefing/Anschreiben beschreibt den KUNDEN (seine Situation, Wünsche, Interessen) — NIEMALS das Objekt. Erwähnt das Briefing ein Konzept/Feature/eine Garantie (z.B. 'Hotelkonzept interessiert', 'will Mietgarantie', 'sucht Meerblick'), darfst du das NICHT als bestätigtes Objekt-Merkmal behaupten ('das Hotelkonzept des Projekts…', 'mit Mietgarantie', 'mit Meerblick'), es sei denn, GENAU dieses Merkmal steht auch in den OBJEKT-Fakten. Du darfst das Kundeninteresse im Anschreiben höchstens als WUNSCH des Kunden spiegeln ('du hast Interesse an…'), nie als Tatsache des Objekts.
5d. KEINE ERFUNDENE VERKNAPPUNG: Behaupte Knappheit/Verfügbarkeit ('nur noch wenige Einheiten', 'eine der letzten', 'fast ausverkauft') NUR, wenn eine konkrete Einheiten-/Verfügbarkeitszahl in den Fakten steht. Steht 'Anzahl Einheiten: keine Angabe' o.ä., formuliere die Reservierungs-CTA neutral ohne Knappheits-Behauptung.
5e. KEINE ERFUNDENEN MARKT-/NACHFRAGE-AUSSAGEN: Aussagen über Mieternachfrage, Zielgruppen, Marktstabilität, 'keine Überhitzung/Blase', erzielbare Mieten, Wertsteigerungs-Tempo oder Lage-Vorzüge (Hügel, Infrastruktur, Ruhe) nur, wenn sie WÖRTLICH in den Fakten stehen. Keine allgemeine Markt-Rhetorik dazudichten.
5f. KEIN WEITERVERKAUF-/EXIT-NARRATIV (HART): Das Deck verkauft ein Objekt zum Eigennutz/zur Vermietung — NICHT als Spekulation. STRIKT VERBOTEN: 'vor Fertigstellung verkaufen', 'Exit-Szenario', 'mit X % Gewinn/Wertzuwachs weiterverkaufen', 'in 2-4 Jahren verkaufen', 'flippen', 'Wiederverkauf mit Gewinn', oder ein eigener Block/Spalten über Verkaufs-/Exit-Strategien. KEINE konkreten Wertsteigerungs-Prozente/Renditen erfinden. Wenn der Kunde im Briefing über Weiterverkauf spricht, NICHT als Objekt-Strategie ausarbeiten.
5b. WAHRHEIT vor Verkauf: Werte Begriffe NICHT auf und kombiniere keine zwei Fakten zu einer stärkeren Aussage. VERBOTEN: aus '5 Jahre Garantie' wird 'Mietgarantie'/'Rendite-Garantie'; aus 'Hotelkonzept' wird 'garantierte Miete'/'gesicherte Auslastung'/'garantierte Rendite'/'sorgt ab dem ersten Tag für Auslastung'/'immer vermietet'/'der Hotelbetreiber kümmert sich um die Vermietung' (es sei denn das steht wörtlich so da). Ein Hotelkonzept ist eine Vermietungs-OPTION, keine Zusicherung auf Miete, Auslastung oder Rendite. Garantien/Renditen/Auslastungen/Belegungsquoten nur nennen, wenn sie WÖRTLICH in den Fakten stehen. Im Zweifel weglassen.`
